# This is the network config written by 'DeuSsd'
network:
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses: [192.168.8.100/24]
      gateway4: 192.168.8.1
  version: 2